-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 21:09:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loja` ;

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`usuario` ;

CREATE TABLE IF NOT EXISTS `loja`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARBINARY(255) NOT NULL,
  `senha` VARBINARY(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `loja`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`produtos` ;

CREATE TABLE IF NOT EXISTS `loja`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
PACK_KEYS = DEFAULT
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `loja`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `loja`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(255) NULL DEFAULT NULL,
  `titulo` VARCHAR(45) NULL DEFAULT NULL,
  `comentario` VARCHAR(255) NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_comentarios_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `loja`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `loja`.`imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`imagem` ;

CREATE TABLE IF NOT EXISTS `loja`.`imagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `imagem` BLOB NOT NULL,
  `produtos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagem_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
INSERT_METHOD = NO;


-- -----------------------------------------------------
-- Table `loja`.`notificacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`notificacoes` ;

CREATE TABLE IF NOT EXISTS `loja`.`notificacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `messagem` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATE NULL DEFAULT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notificacoes_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_notificacoes_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `loja`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`carrinho` ;

CREATE TABLE IF NOT EXISTS `loja`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NULL DEFAULT NULL,
  `produtos_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carrinho_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_carrinho_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `loja`.`produtos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_carrinho_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `loja`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
